BaseURL = "http://localhost:1313"
LanguageCode = "zh-CN"
Title = "walterlv"
Theme = "hugo-pacman-theme"

HasCJKLanguage = true
pygmentsStyle = "default"
pygmentsUseClasses = true

[Author]
  Name = "吕毅"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = "吕毅的博客 walterlv's blog"
  About = "Windows 10 Developer"
  Weibo = "coderzh"
  WeiboID = 1816308191
  Twitter = "coderzh"
  GitHub = "coderzh"
  Facebook = "coderzh"
  LinkIn = "coderzh"
  Imglogo = "img/logo.png"
  AuthorImg = "img/logo.png"
  DateFormat = "2006-01-02 15:04"
  MonthFormat = "2006年01月"
  FancyBox = true

  [Params.GoogleAnalytics]
    ID = "UA-10147768-2"

  [Params.Disqus]
    ShortName = "coderzh"

  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    Rss = "RSS 订阅"
    TableOfContents = "文章目录"

  [Params.Profile]
    Image = "/img/mvp.png"
    Alt = "Microsoft MVP"
    Url = "https://mvp.microsoft.com/en-us/PublicProfile/5003225"
    Hint = "查看我的微软 MVP 主页"

[Menu]
  [[Menu.Main]]
    Name = "朋友"
    URL = "/friends"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
